@host  = http://localhost:5152


GET {{host}}/dinner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYTZlMzE5Yy0xMWFlLTQ1ZWItYTg5Zi1lYTdmZDM1NWZiMmEiLCJnaXZlbl9uYW1lIjoiTmFwb24iLCJmYW1pbHlfbmFtZSI6IlRhbiIsImp0aSI6IjgzNmNlOGVjLTlhYjctNDc0NC1iMTg2LTQ1MDNlN2UwMDc1OCIsImV4cCI6MTc0Njc3NTcwMywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9._F8yJigYWlvaawIwgZHLNPrZcwRGiLMGh5lYjL4wuEg